version: '3.9'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RabbitMQ__HostName=rabbitmq
      - Elasticsearch__Uri=http://elasticsearch:9200
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: on-failure

volumes:
  esdata1:
    driver: local
